# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:00
from __future__ import unicode_literals

from django.db import migrations


def seed_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    maids = Group(name="Waiters")
    maids.save()
    cooks = Group(name="Cooks")
    cooks.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(seed_groups),
    ]
