# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20170319_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cafe.Table'),
            preserve_default=False,
        ),
    ]
