# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0003_bill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='maid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
