# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20170320_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
