# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0008_bill_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('finish', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ManyToManyField(to='cafe.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Table')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='maid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='table',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
