# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_order_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', related_query_name='request', to='cafe.Order'),
        ),
    ]
