# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_auto_20200424_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='menu',
        ),
        migrations.AddField(
            model_name='requestmenu',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Request'),
        ),
    ]
