# Generated by Django 3.0.6 on 2020-05-12 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0011_auto_20200424_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.Table'),
        ),
        migrations.AlterField(
            model_name='request',
            name='maid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', related_query_name='request', to='cafe.Order'),
        ),
        migrations.AlterField(
            model_name='request',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.Table'),
        ),
    ]
