# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_auto_20200507_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='menu',
            field=models.ManyToManyField(through='cafe.RequestMenu', to='cafe.Menu'),
        ),
    ]
