# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_request_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='menu',
        ),
    ]
