# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_remove_request_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='menus',
            field=models.ManyToManyField(through='cafe.RequestMenu', to='cafe.Menu'),
        ),
    ]
