# Generated by Django 3.0.6 on 2020-05-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_auto_20200512_0312'),
        ('cafe', '0015_request_menus'),
    ]

    operations = [
    ]
